### ISSUE TITLE
No idea how this is supposed to work

### ISSUE THREAD

**Issue by nickbe** [petrgrishin/grav-plugin-image-collage#2]
This is my image_collage.yaml:

enabled: true
column: 3
border_size: 10
image_width: 900

Also I've created this simple gallery.html.twig:

<div class="modular-row features {{ page.header.class}}">
    {{ content }}
   {{ images_collage(page.media.images).html }}
</div>

The I'd put several images into a modular subfolder. But the collage does not load.
What am I doing wrong here?

**Comment by Fauphi** [comment]
Same here, it is also not listed in admin-panel under plugins...

**Comment by petrgrishin** [comment]
I found the a bug related to the correction of #1, when installing the plugin through admin panel. 
I'll push fix.

**Comment by nickbe** [comment]
ah.... well. I catually installed the plugin manually. And then couldn't get it to work.

**Comment by petrgrishin** [comment]
It is necessary to replace `image_collage.php` -> `image-collage.php`, `image_collage.yaml` -> `image-collage.yaml`

**Comment by petrgrishin** [comment]
Fixed
