### ISSUE TITLE
Demo request

### ISSUE THREAD

**Issue by Sogl** [petrgrishin/grav-plugin-image-collage#4]
Hello!

Can you make a demo to see how it's working?

**Comment by spadino** [comment]
Hi! Really feels the needs for a demo, or better documentation. Quite interesting plugin...

**Comment by petrgrishin** [comment]
https://github.com/petrgrishin/grav-plugin-image-collage/issues/5#issuecomment-265175510

**Comment by Sogl** [comment]
It's not a demo :wink:
