### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by marcofog** [petrgrishin/grav-plugin-image-collage#5]
Can you give more details?
Where the images should be saved? in which folder?

**Comment by Stepanov-Sergey** [comment]
Open "Pages->Content"
paste content  {{ images_collage(page.media.images, 3,6, 900).html }} 
add images to "Pages>-Content->Page media
and enable twig in "Pages -> Advanced ->twig"
or save images in page folder - for example "user/pages/01.home"
